# Generated by Django 3.1.6 on 2021-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('apartment_id', models.BigIntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('dong', models.TextField(blank=True, null=True)),
                ('jibun', models.TextField(blank=True, null=True)),
                ('apt', models.TextField(blank=True, null=True)),
                ('addr_kr', models.TextField(blank=True, null=True)),
                ('exclusive_use_area', models.FloatField(blank=True, null=True)),
                ('year_of_completion', models.BigIntegerField(blank=True, null=True)),
                ('transaction_year_month', models.BigIntegerField(blank=True, null=True)),
                ('transaction_date', models.TextField(blank=True, null=True)),
                ('floor', models.BigIntegerField(blank=True, null=True)),
                ('transaction_real_price', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gu',
            fields=[
                ('gu_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('gu_num', models.BigIntegerField(blank=True, null=True)),
                ('gu_area', models.FloatField(blank=True, null=True)),
                ('gu_daycare', models.FloatField(blank=True, null=True)),
                ('gu_cctv', models.BigIntegerField(blank=True, null=True)),
                ('gu_mean_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('apartment_id', models.BigIntegerField(blank=True, null=True)),
                ('gu', models.BigIntegerField(blank=True, null=True)),
                ('exclusive_use_area', models.FloatField(blank=True, null=True)),
                ('year_of_completion', models.BigIntegerField(blank=True, null=True)),
                ('transaction_year_month', models.BigIntegerField(blank=True, null=True)),
                ('transaction_date', models.BigIntegerField(blank=True, null=True)),
                ('floor', models.BigIntegerField(blank=True, null=True)),
                ('park_area_sum', models.FloatField(blank=True, null=True)),
                ('day_care_babyteacher_rate', models.FloatField(blank=True, db_column='day_care_babyTeacher_rate', null=True)),
                ('transaction_real_price', models.BigIntegerField(blank=True, null=True)),
                ('cctv_num', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
    ]
