# Generated by Django 3.1.6 on 2021-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('apartment_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, null=True)),
                ('dong', models.TextField(blank=True, null=True)),
                ('jibun', models.TextField(blank=True, null=True)),
                ('apt', models.TextField(blank=True, null=True)),
                ('addr_kr', models.TextField(blank=True, null=True)),
                ('exclusive_use_area', models.FloatField(blank=True, null=True)),
                ('year_of_completion', models.BigIntegerField(blank=True, null=True)),
                ('transaction_year_month', models.BigIntegerField(blank=True, null=True)),
                ('transaction_date', models.TextField(blank=True, null=True)),
                ('floor', models.BigIntegerField(blank=True, null=True)),
                ('transaction_real_price', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_title', models.TextField()),
                ('news_link', models.TextField()),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('apartment_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('gu', models.BigIntegerField(blank=True, null=True)),
                ('exclusive_use_area', models.FloatField(blank=True, null=True)),
                ('year_of_completion', models.BigIntegerField(blank=True, null=True)),
                ('transaction_year_month', models.BigIntegerField(blank=True, null=True)),
                ('transaction_date', models.BigIntegerField(blank=True, null=True)),
                ('floor', models.BigIntegerField(blank=True, null=True)),
                ('park_area_sum', models.FloatField(blank=True, null=True)),
                ('day_care_babyteacher_rate', models.FloatField(blank=True, db_column='day_care_babyTeacher_rate', null=True)),
                ('transaction_real_price', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
    ]
