# Generated by Django 3.1.6 on 2021-04-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayCareCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('gu', models.CharField(blank=True, max_length=45, null=True)),
                ('day_care_name', models.CharField(blank=True, max_length=100, null=True)),
                ('day_care_type', models.CharField(blank=True, max_length=100, null=True)),
                ('day_care_baby_num', models.IntegerField(blank=True, null=True)),
                ('teacher_num', models.IntegerField(blank=True, null=True)),
                ('nursing_room_num', models.IntegerField(blank=True, null=True)),
                ('playground_num', models.IntegerField(blank=True, null=True)),
                ('cctv_num', models.IntegerField(blank=True, db_column='CCTV_num', null=True)),
                ('is_commuting_vehicle', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'day_care_center',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('gu', models.CharField(blank=True, max_length=45, null=True)),
                ('dong', models.CharField(blank=True, max_length=45, null=True)),
                ('park_name', models.CharField(blank=True, max_length=100, null=True)),
                ('park_type', models.CharField(blank=True, max_length=100, null=True)),
                ('park_area', models.IntegerField(blank=True, null=True)),
                ('park_exercise_facility', models.CharField(blank=True, max_length=200, null=True)),
                ('park_entertainment_facility', models.CharField(blank=True, max_length=200, null=True)),
                ('park_benefit_facility', models.CharField(blank=True, max_length=200, null=True)),
                ('park_cultural_facitiy', models.CharField(blank=True, max_length=200, null=True)),
                ('park_facility_other', models.CharField(blank=True, max_length=200, null=True)),
                ('park_open_year', models.TextField(blank=True, null=True)),
                ('reference_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'park',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_real_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('apartment_id', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('dong', models.CharField(blank=True, max_length=45, null=True)),
                ('jibun', models.CharField(blank=True, max_length=45, null=True)),
                ('apt', models.CharField(blank=True, max_length=45, null=True)),
                ('addr_kr', models.CharField(blank=True, max_length=45, null=True)),
                ('exclusive_use_area', models.FloatField(blank=True, null=True)),
                ('year_of_completion', models.TextField(blank=True, null=True)),
                ('transaction_year_month', models.DateField(blank=True, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=45, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('transaction_real_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='predictapp.submission')),
                ('apartment_id', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('dong', models.CharField(blank=True, max_length=45, null=True)),
                ('jibun', models.CharField(blank=True, max_length=45, null=True)),
                ('apt', models.CharField(blank=True, max_length=250, null=True)),
                ('addr_kr', models.CharField(blank=True, max_length=250, null=True)),
                ('exclusive_use_area', models.FloatField(blank=True, null=True)),
                ('year_of_completion', models.TextField(blank=True, null=True)),
                ('transaction_year_month', models.DateField(blank=True, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=45, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
