# Generated by Django 3.1.6 on 2021-04-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayCareCenter',
        ),
        migrations.DeleteModel(
            name='Park',
        ),
        migrations.RemoveField(
            model_name='test',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
