# Generated by Django 3.1.6 on 2021-04-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu_name', models.TextField(blank=True, null=True)),
                ('gu_num', models.BigIntegerField(blank=True, null=True)),
                ('gu_area', models.FloatField(blank=True, null=True)),
                ('gu_daycare', models.FloatField(blank=True, null=True)),
                ('gu_cctv', models.BigIntegerField(blank=True, null=True)),
                ('gu_mean_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gu',
                'managed': False,
            },
        ),
    ]
