# Generated by Django 3.1.6 on 2021-04-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField(blank=True, null=True)),
                ('news_title', models.TextField()),
                ('news_link', models.TextField()),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
