# Generated by Django 3.1.6 on 2021-04-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0002_auto_20210405_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Train',
        ),
    ]
