# Generated by Django 3.1.6 on 2021-04-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictapp', '0003_delete_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_id', models.IntegerField(blank=True, null=True)),
                ('gu', models.IntegerField(blank=True, null=True)),
                ('exclusive_use_area', models.FloatField(blank=True, null=True)),
                ('year_of_completion', models.IntegerField(blank=True, null=True)),
                ('transaction_year_month', models.IntegerField(blank=True, null=True)),
                ('transaction_date', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('park_area_sum', models.FloatField(blank=True, null=True)),
                ('day_care_babyteacher_rate', models.FloatField(blank=True, db_column='day_care_babyTeacher_rate', null=True)),
                ('transaction_real_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
    ]
